# Generated by Django 3.1.5 on 2021-02-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=120)),
                ('spend', models.CharField(max_length=120)),
                ('StartDate', models.CharField(max_length=120)),
                ('EndDate', models.CharField(max_length=120)),
            ],
        ),
    ]
